### ISSUE TITLE
## Create Product List

### ISSUE THREAD

**Issue by heinenandreas** [heinenandreas/Capstone-App-Pantry#1]
**As a User** 
**I need** to see a list of my stored products
**to to have an overview over my existing items

## Description

A list of items should be displayed

## Acceptance Criteria

- [ ] An object should be displayed as a list
- [ ] it contains a product name, packing unit and the amount of each item

## Tasks

- [ ] map over a (placeholder-) list
